sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
sudo python3 run_inits.py 6
