sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
sudo python3 run_inits.py 2
