sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
sudo python3 run_inits.py 4
