sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
sudo python3 run_inits.py 5
