sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
sudo python3 run_inits.py 3
